# This is a basic workflow to help you get started with Actions

name: Merge FE
on:
  pull_request:
    types:
      - opened
    branches:
      - 'FE/**'
jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: yarn install
        run: |
          cd frontend
          yarn install
          
      - name: yarn build
        run: |
          cd frontend
          mkdir build
        # yarn build 
        
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
          #role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          #role-external-id: ${{ secrets.AWS_ROLE_EXTERNAL_ID }}
          
      - name: List configurations
        run: aws configure list

      - name: Deploy
        run: |
          cd frontend
          yarn deploy      
        
