# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  Build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: yarn install
        run: |
          cd frontend
          yarn install
          
      - name: yarn build
        run: |
          cd frontend
          yarn build
          
        
  Deploy:
      needs: Build
      runs-on: ubuntu-latest
      steps:
        - name: install-aws-cli-action
          uses: unfor19/install-aws-cli-action@v1.0.3
        - name: AWS configure
          run: |
            aws configure set aws_access_key_id default_access_key
            aws configure set aws_secret_access_key default_secret_key
            aws configure set default.region eu-central-1
            aws configure set profile.novu.region eu-central-1
            aws configure set default.output json
            aws configure set profile.novu.output json
              
        - name: List configurations
          run: aws configure list
          
        - name: Deploy
          run: aws --profile novu s3 sync build/ s3://getnovu.com
          
      
