name: Build and Deploy on push to master
on:
   push:
      branches:
         - main
    
jobs:
  Build:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: install-aws-cli-action
        uses: unfor19/install-aws-cli-action@v1.0.3
        
      - name: AWS configure
        run: |
          aws configure set aws_access_key_id default_access_key
          aws configure set aws_secret_access_key default_secret_key
          aws configure set default.region eu-central-1
          aws configure set profile.novu.region eu-central-1
              
      - name: List configurations
        run: aws configure list
        
      - name: yarn install
        run: |
          cd frontend
          yarn install
          
      - name: yarn build
        run: |
          cd frontend
          yarn build     

      - name: Deploy
        run: |
          cd frontend
          yarn deploy      
        
        
